updated fedora script so that exit code 100 is not stopping script. Added dnf update.

diff --git a/.chezmoiscripts/run_once_before_install_fedora.sh.tmpl b/.chezmoiscripts/run_once_before_install_fedora.sh.tmpl
--- a/.chezmoiscripts/run_once_before_install_fedora.sh.tmpl
+++ b/.chezmoiscripts/run_once_before_install_fedora.sh.tmpl
@@ -3,6 +3,21 @@
 echo ""
 echo "==============================================================="
 echo ""
+echo "Checking outdated packages"
+echo ""
+echo "==============================================================="
+echo ""
+
+sudo dnf check-update > /dev/null 2>&1 && 
+if [ $? -eq 100 ]; then
+    echo "Updates are available."
+    sudo dnf -y update
+fi &&
+
+
+echo ""
+echo "==============================================================="
+echo ""
 echo "Setting Kitty shortcuts"
 echo ""
 echo "==============================================================="
@@ -53,7 +68,11 @@ echo ""
 
 sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc &&
 echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\nautorefresh=1\ntype=rpm-md\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" | sudo tee /etc/yum.repos.d/vscode.repo > /dev/null
-sudo dnf check-update &&
-sudo dnf -y install code # or code-insiders
+#prevent exit code 100 from exiting.
+sudo dnf check-update > /dev/null 2>&1 && 
+if [ $? -eq 100 ]; then
+    echo "Updates are available."
+fi &&
+sudo dnf -y install code
 
 {{- end -}}
