add snap and glab

diff --git a/.chezmoiscripts/run_once_before_install_ubuntu_packages.sh.tmpl b/.chezmoiscripts/run_once_before_install_ubuntu_packages.sh.tmpl
--- a/.chezmoiscripts/run_once_before_install_ubuntu_packages.sh.tmpl
+++ b/.chezmoiscripts/run_once_before_install_ubuntu_packages.sh.tmpl
@@ -11,7 +11,6 @@ packages=(
     findutils
     git
     gh
-    gitlab-cli
     neovim
     jq
     tmux
@@ -19,6 +18,7 @@ packages=(
     tree
     unzip
     gcc
+    snapd
 )
 
 for package in "${packages[@]}"; do
@@ -43,6 +43,12 @@ fi
 if ! check_package starship; then
   echo "starship not found!"
   curl -sS https://starship.rs/install.sh | sh
+fi
+
+## install glab
+if ! check_package glab; then
+  echo "glab not found!"
+  sudo snap install glab
 fi
 
 {{ end -}}
